# -*- coding: utf-8 -*-
"""00_helloWorld.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17G3qqBO4iER4WZULgZo0jwy1gdlIq-JZ
"""

# Este simbolo se utiliza para comentar el codigo
print( "hola grupo 230 de la carrera tecnica de PROGRAMACIÓN" )
como consutar el tipo de datos
print(type("soy un dato str")) # Tipo 'str'
print(type(5)) # tipo 'int'
print(type(1.5)) # tipo 'float'
print(type(3 + 1j)) # tipo 'conplex'
print(type(true)) # tipo 'bool´
print(type(print("mi cadena de textos")))