# -*- coding: utf-8 -*-
"""01_variables.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1msbrmLt_dqwlu10YfNNeRRgSBRxRfFZf
"""

### Variables ###

my_string_variable= "My String variable"
print(my_string_variable)

my_int_variable = 5
print(my_int_variable)

my_int_to_str__variable = str(my_int_variable)
print(my_int_to_str__variable)
print(type(my_int_to_str__variable))

my_bool_variable= False
print(my_bool_variable)

